# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-12-02 17:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20181128_2156'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userfile',
            name='Image',
            field=models.ImageField(default='image/default.png', upload_to='image/%y/%m', verbose_name='头像'),
        ),
        migrations.AlterField(
            model_name='userfile',
            name='gender',
            field=models.CharField(choices=[('male', '男'), ('female', '女')], default='female', max_length=6, verbose_name='性别'),
        ),
    ]
